### Query string items filtered by Tags and Angular
POST http://localhost:4280/data-api/graphql
Content-Type: application/json

{
    "query": "query GetAll { stringItems(filter: {PartitionKey: {eq: \"Tags\"}}) { items { id PartitionKey } } }"
}


### Query string items filtered by Tags and Angular
POST https://black-bay-008792203.6.azurestaticapps.net//data-api/graphql
Content-Type: application/json

{
    "query": "query GetAll { stringItems(filter: {PartitionKey: {eq: \"Tags\"}}) { items { id PartitionKey } } }"
}
